require("plugins-setup")
require("core.options")
require("core.keymaps")
require("core.colorscheme")
-- plugins-setup
require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.autopairs")
require("plugins.treesitter")
-- lsp-setup
require("plugins.lsp.mason")
require("plugins.lsp.lspconfig")
require("plugins.lsp.lspsaga")
require("plugins.lsp.null-ls")
